// This file is automatically generated, do not edit!
// Run scripts/generate-atp-schema.js to update this file.

export type CID = string;

export type DID = `did:${string}`;

export type Handle = string;

export type AtUri = string;

export type AtIdentifier = AtUri | Handle;

export interface AtBlob<T extends string = string> {
	$type: 'blob';
	mimeType: T;
	ref: {
		$link: string;
	};
	size: number;
}

export type ResponseOf<K extends keyof Queries | keyof Procedures> = K extends keyof Queries
	? Queries[K] extends { response: any }
		? Queries[K]['response']
		: unknown
	: K extends keyof Procedures
		? Procedures[K] extends { response: any }
			? Procedures[K]['response']
			: unknown
		: never;

export type RefOf<K extends keyof Objects> = Objects[K];
export type UnionOf<K extends keyof Objects> = Objects[K] & { $type: K };

export interface Queries {
	/**
	 * Get private preferences attached to the current account. Expected use is synchronization between multiple devices, and import/export during account migration. Requires auth.
	 */
	'app.bsky.actor.getPreferences': {
		response: {
			preferences: RefOf<'app.bsky.actor.defs#preferences'>;
		};
	};
	/**
	 * Get detailed profile view of an actor. Does not require auth, but contains relevant metadata with auth.
	 */
	'app.bsky.actor.getProfile': {
		params: {
			/**
			 * Handle or DID of account to fetch profile of.
			 */
			actor: string;
		};
		response: RefOf<'app.bsky.actor.defs#profileViewDetailed'>;
	};
	/**
	 * Get detailed profile views of multiple actors.
	 */
	'app.bsky.actor.getProfiles': {
		params: {
			/**
			 * Maximum array length: 25
			 */
			actors: string[];
		};
		response: {
			profiles: RefOf<'app.bsky.actor.defs#profileViewDetailed'>[];
		};
	};
	/**
	 * Get a list of suggested actors. Expected use is discovery of accounts to follow during new account onboarding.
	 */
	'app.bsky.actor.getSuggestions': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			actors: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Find actors (profiles) matching search criteria. Does not require auth.
	 */
	'app.bsky.actor.searchActors': {
		params: {
			/**
			 * DEPRECATED: use 'q' instead.
			 * @deprecated
			 */
			term?: string;
			/**
			 * Search query string. Syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
			 */
			q?: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 25
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			actors: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Find actor suggestions for a prefix search term. Expected use is for auto-completion during text field entry. Does not require auth.
	 */
	'app.bsky.actor.searchActorsTypeahead': {
		params: {
			/**
			 * DEPRECATED: use 'q' instead.
			 * @deprecated
			 */
			term?: string;
			/**
			 * Search query prefix; not a full query string.
			 */
			q?: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 10
			 */
			limit?: number;
		};
		response: {
			actors: RefOf<'app.bsky.actor.defs#profileViewBasic'>[];
		};
	};
	/**
	 * Get information about a feed generator, including policies and offered feed URIs. Does not require auth; implemented by Feed Generator services (not App View).
	 */
	'app.bsky.feed.describeFeedGenerator': {
		response: {
			did: DID;
			feeds: RefOf<'app.bsky.feed.describeFeedGenerator#feed'>[];
			links?: RefOf<'app.bsky.feed.describeFeedGenerator#links'>;
		};
	};
	/**
	 * Get a list of feeds (feed generator records) created by the actor (in the actor's repo).
	 */
	'app.bsky.feed.getActorFeeds': {
		params: {
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feeds: RefOf<'app.bsky.feed.defs#generatorView'>[];
		};
	};
	/**
	 * Get a list of posts liked by an actor. Does not require auth.
	 */
	'app.bsky.feed.getActorLikes': {
		params: {
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#feedViewPost'>[];
		};
		errors: {
			BlockedActor: {};
			BlockedByActor: {};
		};
	};
	/**
	 * Get a view of an actor's 'author feed' (post and reposts by the author). Does not require auth.
	 */
	'app.bsky.feed.getAuthorFeed': {
		params: {
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
			/**
			 * Combinations of post/repost types to include in response.
			 * @default "posts_with_replies"
			 */
			filter?:
				| 'posts_with_replies'
				| 'posts_no_replies'
				| 'posts_with_media'
				| 'posts_and_author_threads'
				| (string & {});
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#feedViewPost'>[];
		};
		errors: {
			BlockedActor: {};
			BlockedByActor: {};
		};
	};
	/**
	 * Get a hydrated feed from an actor's selected feed generator. Implemented by App View.
	 */
	'app.bsky.feed.getFeed': {
		params: {
			feed: AtUri;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#feedViewPost'>[];
		};
		errors: {
			UnknownFeed: {};
		};
	};
	/**
	 * Get information about a feed generator. Implemented by AppView.
	 */
	'app.bsky.feed.getFeedGenerator': {
		params: {
			/**
			 * AT-URI of the feed generator record.
			 */
			feed: AtUri;
		};
		response: {
			view: RefOf<'app.bsky.feed.defs#generatorView'>;
			/**
			 * Indicates whether the feed generator service has been online recently, or else seems to be inactive.
			 */
			isOnline: boolean;
			/**
			 * Indicates whether the feed generator service is compatible with the record declaration.
			 */
			isValid: boolean;
		};
	};
	/**
	 * Get information about a list of feed generators.
	 */
	'app.bsky.feed.getFeedGenerators': {
		params: {
			feeds: AtUri[];
		};
		response: {
			feeds: RefOf<'app.bsky.feed.defs#generatorView'>[];
		};
	};
	/**
	 * Get a skeleton of a feed provided by a feed generator. Auth is optional, depending on provider requirements, and provides the DID of the requester. Implemented by Feed Generator Service.
	 */
	'app.bsky.feed.getFeedSkeleton': {
		params: {
			/**
			 * Reference to feed generator record describing the specific feed being requested.
			 */
			feed: AtUri;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#skeletonFeedPost'>[];
		};
		errors: {
			UnknownFeed: {};
		};
	};
	/**
	 * Get like records which reference a subject (by AT-URI and CID).
	 */
	'app.bsky.feed.getLikes': {
		params: {
			/**
			 * AT-URI of the subject (eg, a post record).
			 */
			uri: AtUri;
			/**
			 * CID of the subject record (aka, specific version of record), to filter likes.
			 */
			cid?: CID;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			uri: AtUri;
			cid?: CID;
			cursor?: string;
			likes: RefOf<'app.bsky.feed.getLikes#like'>[];
		};
	};
	/**
	 * Get a feed of recent posts from a list (posts and reposts from any actors on the list). Does not require auth.
	 */
	'app.bsky.feed.getListFeed': {
		params: {
			/**
			 * Reference (AT-URI) to the list record.
			 */
			list: AtUri;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#feedViewPost'>[];
		};
		errors: {
			UnknownList: {};
		};
	};
	/**
	 * Get posts in a thread. Does not require auth, but additional metadata and filtering will be applied for authed requests.
	 */
	'app.bsky.feed.getPostThread': {
		params: {
			/**
			 * Reference (AT-URI) to post record.
			 */
			uri: AtUri;
			/**
			 * How many levels of reply depth should be included in response. \
			 * Minimum: 0 \
			 * Maximum: 1000
			 * @default 6
			 */
			depth?: number;
			/**
			 * How many levels of parent (and grandparent, etc) post to include. \
			 * Minimum: 0 \
			 * Maximum: 1000
			 * @default 80
			 */
			parentHeight?: number;
		};
		response: {
			thread:
				| UnionOf<'app.bsky.feed.defs#threadViewPost'>
				| UnionOf<'app.bsky.feed.defs#notFoundPost'>
				| UnionOf<'app.bsky.feed.defs#blockedPost'>;
		};
		errors: {
			NotFound: {};
		};
	};
	/**
	 * Gets post views for a specified list of posts (by AT-URI). This is sometimes referred to as 'hydrating' a 'feed skeleton'.
	 */
	'app.bsky.feed.getPosts': {
		params: {
			/**
			 * List of post AT-URIs to return hydrated views for. \
			 * Maximum array length: 25
			 */
			uris: AtUri[];
		};
		response: {
			posts: RefOf<'app.bsky.feed.defs#postView'>[];
		};
	};
	/**
	 * Get a list of reposts for a given post.
	 */
	'app.bsky.feed.getRepostedBy': {
		params: {
			/**
			 * Reference (AT-URI) of post record
			 */
			uri: AtUri;
			/**
			 * If supplied, filters to reposts of specific version (by CID) of the post record.
			 */
			cid?: CID;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			uri: AtUri;
			cid?: CID;
			cursor?: string;
			repostedBy: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Get a list of suggested feeds (feed generators) for the requesting account.
	 */
	'app.bsky.feed.getSuggestedFeeds': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feeds: RefOf<'app.bsky.feed.defs#generatorView'>[];
		};
	};
	/**
	 * Get a view of the requesting account's home timeline. This is expected to be some form of reverse-chronological feed.
	 */
	'app.bsky.feed.getTimeline': {
		params: {
			/**
			 * Variant 'algorithm' for timeline. Implementation-specific. NOTE: most feed flexibility has been moved to feed generator mechanism.
			 */
			algorithm?: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			feed: RefOf<'app.bsky.feed.defs#feedViewPost'>[];
		};
	};
	/**
	 * Find posts matching search criteria, returning views of those posts.
	 */
	'app.bsky.feed.searchPosts': {
		params: {
			/**
			 * Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
			 */
			q: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 25
			 */
			limit?: number;
			/**
			 * Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
			 */
			cursor?: string;
		};
		response: {
			cursor?: string;
			/**
			 * Count of search hits. Optional, may be rounded/truncated, and may not be possible to paginate through all hits.
			 */
			hitsTotal?: number;
			posts: RefOf<'app.bsky.feed.defs#postView'>[];
		};
		errors: {
			BadQueryString: {};
		};
	};
	/**
	 * Enumerates which accounts the requesting account is currently blocking. Requires auth.
	 */
	'app.bsky.graph.getBlocks': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			blocks: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Enumerates accounts which follow a specified account (actor).
	 */
	'app.bsky.graph.getFollowers': {
		params: {
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			subject: RefOf<'app.bsky.actor.defs#profileView'>;
			cursor?: string;
			followers: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Enumerates accounts which a specified account (actor) follows.
	 */
	'app.bsky.graph.getFollows': {
		params: {
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			subject: RefOf<'app.bsky.actor.defs#profileView'>;
			cursor?: string;
			follows: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Gets a 'view' (with additional context) of a specified list.
	 */
	'app.bsky.graph.getList': {
		params: {
			/**
			 * Reference (AT-URI) of the list record to hydrate.
			 */
			list: AtUri;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			list: RefOf<'app.bsky.graph.defs#listView'>;
			items: RefOf<'app.bsky.graph.defs#listItemView'>[];
		};
	};
	/**
	 * Get mod lists that the requesting account (actor) is blocking. Requires auth.
	 */
	'app.bsky.graph.getListBlocks': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			lists: RefOf<'app.bsky.graph.defs#listView'>[];
		};
	};
	/**
	 * Enumerates mod lists that the requesting account (actor) currently has muted. Requires auth.
	 */
	'app.bsky.graph.getListMutes': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			lists: RefOf<'app.bsky.graph.defs#listView'>[];
		};
	};
	/**
	 * Enumerates the lists created by a specified account (actor).
	 */
	'app.bsky.graph.getLists': {
		params: {
			/**
			 * The account (actor) to enumerate lists from.
			 */
			actor: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			lists: RefOf<'app.bsky.graph.defs#listView'>[];
		};
	};
	/**
	 * Enumerates accounts that the requesting account (actor) currently has muted. Requires auth.
	 */
	'app.bsky.graph.getMutes': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			mutes: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Enumerates public relationships between one account, and a list of other accounts. Does not require auth.
	 */
	'app.bsky.graph.getRelationships': {
		params: {
			/**
			 * Primary account requesting relationships for.
			 */
			actor: string;
			/**
			 * List of 'other' accounts to be related back to the primary. \
			 * Maximum array length: 30
			 */
			others?: string[];
		};
		response: {
			actor?: DID;
			relationships: (
				| UnionOf<'app.bsky.graph.defs#relationship'>
				| UnionOf<'app.bsky.graph.defs#notFoundActor'>
			)[];
		};
		errors: {
			ActorNotFound: {};
		};
	};
	/**
	 * Enumerates follows similar to a given account (actor). Expected use is to recommend additional accounts immediately after following one account.
	 */
	'app.bsky.graph.getSuggestedFollowsByActor': {
		params: {
			actor: string;
		};
		response: {
			suggestions: RefOf<'app.bsky.actor.defs#profileView'>[];
		};
	};
	/**
	 * Count the number of unread notifications for the requesting account. Requires auth.
	 */
	'app.bsky.notification.getUnreadCount': {
		params: {
			seenAt?: string;
		};
		response: {
			count: number;
		};
	};
	/**
	 * Enumerate notifications for the requesting account. Requires auth.
	 */
	'app.bsky.notification.listNotifications': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
			seenAt?: string;
		};
		response: {
			cursor?: string;
			notifications: RefOf<'app.bsky.notification.listNotifications#notification'>[];
			seenAt?: string;
		};
	};
	/**
	 * An unspecced view of globally popular feed generators.
	 */
	'app.bsky.unspecced.getPopularFeedGenerators': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
			query?: string;
		};
		response: {
			cursor?: string;
			feeds: RefOf<'app.bsky.feed.defs#generatorView'>[];
		};
	};
	/**
	 * Get a list of suggestions (feeds and users) tagged with categories
	 */
	'app.bsky.unspecced.getTaggedSuggestions': {
		response: {
			suggestions: RefOf<'app.bsky.unspecced.getTaggedSuggestions#suggestion'>[];
		};
	};
	/**
	 * Backend Actors (profile) search, returns only skeleton.
	 */
	'app.bsky.unspecced.searchActorsSkeleton': {
		params: {
			/**
			 * Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended. For typeahead search, only simple term match is supported, not full syntax.
			 */
			q: string;
			/**
			 * If true, acts as fast/simple 'typeahead' query.
			 */
			typeahead?: boolean;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 25
			 */
			limit?: number;
			/**
			 * Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
			 */
			cursor?: string;
		};
		response: {
			cursor?: string;
			/**
			 * Count of search hits. Optional, may be rounded/truncated, and may not be possible to paginate through all hits.
			 */
			hitsTotal?: number;
			actors: RefOf<'app.bsky.unspecced.defs#skeletonSearchActor'>[];
		};
		errors: {
			BadQueryString: {};
		};
	};
	/**
	 * Backend Posts search, returns only skeleton
	 */
	'app.bsky.unspecced.searchPostsSkeleton': {
		params: {
			/**
			 * Search query string; syntax, phrase, boolean, and faceting is unspecified, but Lucene query syntax is recommended.
			 */
			q: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 25
			 */
			limit?: number;
			/**
			 * Optional pagination mechanism; may not necessarily allow scrolling through entire result set.
			 */
			cursor?: string;
		};
		response: {
			cursor?: string;
			/**
			 * Count of search hits. Optional, may be rounded/truncated, and may not be possible to paginate through all hits.
			 */
			hitsTotal?: number;
			posts: RefOf<'app.bsky.unspecced.defs#skeletonSearchPost'>[];
		};
		errors: {
			BadQueryString: {};
		};
	};
	/**
	 * Get details about an account.
	 */
	'com.atproto.admin.getAccountInfo': {
		params: {
			did: DID;
		};
		response: RefOf<'com.atproto.admin.defs#accountView'>;
	};
	/**
	 * Get details about some accounts.
	 */
	'com.atproto.admin.getAccountInfos': {
		params: {
			dids: DID[];
		};
		response: {
			infos: RefOf<'com.atproto.admin.defs#accountView'>[];
		};
	};
	/**
	 * Get an admin view of invite codes.
	 */
	'com.atproto.admin.getInviteCodes': {
		params: {
			/**
			 * @default "recent"
			 */
			sort?: 'recent' | 'usage' | (string & {});
			/**
			 * Minimum: 1 \
			 * Maximum: 500
			 * @default 100
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			codes: RefOf<'com.atproto.server.defs#inviteCode'>[];
		};
	};
	/**
	 * Get details about a moderation event.
	 */
	'com.atproto.admin.getModerationEvent': {
		params: {
			id: number;
		};
		response: RefOf<'com.atproto.admin.defs#modEventViewDetail'>;
	};
	/**
	 * Get details about a record.
	 */
	'com.atproto.admin.getRecord': {
		params: {
			uri: AtUri;
			cid?: CID;
		};
		response: RefOf<'com.atproto.admin.defs#recordViewDetail'>;
		errors: {
			RecordNotFound: {};
		};
	};
	/**
	 * Get details about a repository.
	 */
	'com.atproto.admin.getRepo': {
		params: {
			did: DID;
		};
		response: RefOf<'com.atproto.admin.defs#repoViewDetail'>;
		errors: {
			RepoNotFound: {};
		};
	};
	/**
	 * Get the service-specific admin status of a subject (account, record, or blob).
	 */
	'com.atproto.admin.getSubjectStatus': {
		params: {
			did?: DID;
			uri?: AtUri;
			blob?: CID;
		};
		response: {
			subject:
				| UnionOf<'com.atproto.admin.defs#repoRef'>
				| UnionOf<'com.atproto.repo.strongRef'>
				| UnionOf<'com.atproto.admin.defs#repoBlobRef'>;
			takedown?: RefOf<'com.atproto.admin.defs#statusAttr'>;
		};
	};
	/**
	 * Get list of all communication templates.
	 */
	'com.atproto.admin.listCommunicationTemplates': {
		response: {
			communicationTemplates: RefOf<'com.atproto.admin.defs#communicationTemplateView'>[];
		};
	};
	/**
	 * List moderation events related to a subject.
	 */
	'com.atproto.admin.queryModerationEvents': {
		params: {
			/**
			 * The types of events (fully qualified string in the format of com.atproto.admin#modEvent<name>) to filter by. If not specified, all events are returned.
			 */
			types?: string[];
			createdBy?: DID;
			/**
			 * Sort direction for the events. Defaults to descending order of created at timestamp.
			 * @default "desc"
			 */
			sortDirection?: string;
			/**
			 * Retrieve events created after a given timestamp
			 */
			createdAfter?: string;
			/**
			 * Retrieve events created before a given timestamp
			 */
			createdBefore?: string;
			subject?: string;
			/**
			 * If true, events on all record types (posts, lists, profile etc.) owned by the did are returned
			 * @default false
			 */
			includeAllUserRecords?: boolean;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			/**
			 * If true, only events with comments are returned
			 */
			hasComment?: boolean;
			/**
			 * If specified, only events with comments containing the keyword are returned
			 */
			comment?: string;
			/**
			 * If specified, only events where all of these labels were added are returned
			 */
			addedLabels?: string[];
			/**
			 * If specified, only events where all of these labels were removed are returned
			 */
			removedLabels?: string[];
			/**
			 * If specified, only events where all of these tags were added are returned
			 */
			addedTags?: string[];
			/**
			 * If specified, only events where all of these tags were removed are returned
			 */
			removedTags?: string[];
			reportTypes?: string[];
			cursor?: string;
		};
		response: {
			cursor?: string;
			events: RefOf<'com.atproto.admin.defs#modEventView'>[];
		};
	};
	/**
	 * View moderation statuses of subjects (record or repo).
	 */
	'com.atproto.admin.queryModerationStatuses': {
		params: {
			subject?: string;
			/**
			 * Search subjects by keyword from comments
			 */
			comment?: string;
			/**
			 * Search subjects reported after a given timestamp
			 */
			reportedAfter?: string;
			/**
			 * Search subjects reported before a given timestamp
			 */
			reportedBefore?: string;
			/**
			 * Search subjects reviewed after a given timestamp
			 */
			reviewedAfter?: string;
			/**
			 * Search subjects reviewed before a given timestamp
			 */
			reviewedBefore?: string;
			/**
			 * By default, we don't include muted subjects in the results. Set this to true to include them.
			 */
			includeMuted?: boolean;
			/**
			 * Specify when fetching subjects in a certain state
			 */
			reviewState?: string;
			ignoreSubjects?: string[];
			/**
			 * Get all subject statuses that were reviewed by a specific moderator
			 */
			lastReviewedBy?: DID;
			/**
			 * @default "lastReportedAt"
			 */
			sortField?: string;
			/**
			 * @default "desc"
			 */
			sortDirection?: string;
			/**
			 * Get subjects that were taken down
			 */
			takendown?: boolean;
			/**
			 * Get subjects in unresolved appealed status
			 */
			appealed?: boolean;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			tags?: string[];
			excludeTags?: string[];
			cursor?: string;
		};
		response: {
			cursor?: string;
			subjectStatuses: RefOf<'com.atproto.admin.defs#subjectStatusView'>[];
		};
	};
	/**
	 * Find repositories based on a search term.
	 */
	'com.atproto.admin.searchRepos': {
		params: {
			/**
			 * DEPRECATED: use 'q' instead
			 * @deprecated
			 */
			term?: string;
			q?: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			repos: RefOf<'com.atproto.admin.defs#repoView'>[];
		};
	};
	/**
	 * Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
	 */
	'com.atproto.identity.getRecommendedDidCredentials': {
		response: {
			/**
			 * Recommended rotation keys for PLC dids. Should be undefined (or ignored) for did:webs.
			 */
			rotationKeys?: string[];
			alsoKnownAs?: string[];
			verificationMethods?: unknown;
			services?: unknown;
		};
	};
	/**
	 * Resolves a handle (domain name) to a DID.
	 */
	'com.atproto.identity.resolveHandle': {
		params: {
			/**
			 * The handle to resolve.
			 */
			handle: Handle;
		};
		response: {
			did: DID;
		};
	};
	/**
	 * Find labels relevant to the provided AT-URI patterns. Public endpoint for moderation services, though may return different or additional results with auth.
	 */
	'com.atproto.label.queryLabels': {
		params: {
			/**
			 * List of AT URI patterns to match (boolean 'OR'). Each may be a prefix (ending with '*'; will match inclusive of the string leading to '*'), or a full URI.
			 */
			uriPatterns: string[];
			/**
			 * Optional list of label sources (DIDs) to filter on.
			 */
			sources?: DID[];
			/**
			 * Minimum: 1 \
			 * Maximum: 250
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			labels: RefOf<'com.atproto.label.defs#label'>[];
		};
	};
	/**
	 * Get information about an account and repository, including the list of collections. Does not require auth.
	 */
	'com.atproto.repo.describeRepo': {
		params: {
			/**
			 * The handle or DID of the repo.
			 */
			repo: string;
		};
		response: {
			handle: Handle;
			did: DID;
			/**
			 * The complete DID document for this account.
			 */
			didDoc: unknown;
			/**
			 * List of all the collections (NSIDs) for which this repo contains at least one record.
			 */
			collections: string[];
			/**
			 * Indicates if handle is currently valid (resolves bi-directionally)
			 */
			handleIsCorrect: boolean;
		};
	};
	/**
	 * Get a single record from a repository. Does not require auth.
	 */
	'com.atproto.repo.getRecord': {
		params: {
			/**
			 * The handle or DID of the repo.
			 */
			repo: string;
			/**
			 * The NSID of the record collection.
			 */
			collection: string;
			/**
			 * The Record Key.
			 */
			rkey: string;
			/**
			 * The CID of the version of the record. If not specified, then return the most recent version.
			 */
			cid?: CID;
		};
		response: {
			uri: AtUri;
			cid?: CID;
			value: unknown;
		};
	};
	/**
	 * Returns a list of missing blobs for the requesting account. Intended to be used in the account migration flow.
	 */
	'com.atproto.repo.listMissingBlobs': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 1000
			 * @default 500
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			blobs: RefOf<'com.atproto.repo.listMissingBlobs#recordBlob'>[];
		};
	};
	/**
	 * List a range of records in a repository, matching a specific collection. Does not require auth.
	 */
	'com.atproto.repo.listRecords': {
		params: {
			/**
			 * The handle or DID of the repo.
			 */
			repo: string;
			/**
			 * The NSID of the record type.
			 */
			collection: string;
			/**
			 * The number of records to return. \
			 * Minimum: 1 \
			 * Maximum: 100
			 * @default 50
			 */
			limit?: number;
			cursor?: string;
			/**
			 * DEPRECATED: The lowest sort-ordered rkey to start from (exclusive)
			 * @deprecated
			 */
			rkeyStart?: string;
			/**
			 * DEPRECATED: The highest sort-ordered rkey to stop at (exclusive)
			 * @deprecated
			 */
			rkeyEnd?: string;
			/**
			 * Flag to reverse the order of the returned records.
			 */
			reverse?: boolean;
		};
		response: {
			cursor?: string;
			records: RefOf<'com.atproto.repo.listRecords#record'>[];
		};
	};
	/**
	 * Returns the status of an account, especially as pertaining to import or recovery. Can be called many times over the course of an account migration. Requires auth and can only be called pertaining to oneself.
	 */
	'com.atproto.server.checkAccountStatus': {
		response: {
			activated: boolean;
			validDid: boolean;
			repoCommit: CID;
			repoRev: string;
			repoBlocks: number;
			indexedRecords: number;
			privateStateValues: number;
			expectedBlobs: number;
			importedBlobs: number;
		};
	};
	/**
	 * Describes the server's account creation requirements and capabilities. Implemented by PDS.
	 */
	'com.atproto.server.describeServer': {
		response: {
			/**
			 * If true, an invite code must be supplied to create an account on this instance.
			 */
			inviteCodeRequired?: boolean;
			/**
			 * If true, a phone verification token must be supplied to create an account on this instance.
			 */
			phoneVerificationRequired?: boolean;
			/**
			 * List of domain suffixes that can be used in account handles.
			 */
			availableUserDomains: string[];
			/**
			 * URLs of service policy documents.
			 */
			links?: RefOf<'com.atproto.server.describeServer#links'>;
			did: DID;
		};
	};
	/**
	 * Get all invite codes for the current account. Requires auth.
	 */
	'com.atproto.server.getAccountInviteCodes': {
		params: {
			/**
			 * @default true
			 */
			includeUsed?: boolean;
			/**
			 * Controls whether any new 'earned' but not 'created' invites should be created.
			 * @default true
			 */
			createAvailable?: boolean;
		};
		response: {
			codes: RefOf<'com.atproto.server.defs#inviteCode'>[];
		};
		errors: {
			DuplicateCreate: {};
		};
	};
	/**
	 * Get a signed token on behalf of the requesting DID for the requested service.
	 */
	'com.atproto.server.getServiceAuth': {
		params: {
			/**
			 * The DID of the service that the token will be used to authenticate with
			 */
			aud: DID;
		};
		response: {
			token: string;
		};
	};
	/**
	 * Get information about the current auth session. Requires auth.
	 */
	'com.atproto.server.getSession': {
		response: {
			handle: Handle;
			did: DID;
			email?: string;
			emailConfirmed?: boolean;
			didDoc?: unknown;
		};
	};
	/**
	 * List all App Passwords.
	 */
	'com.atproto.server.listAppPasswords': {
		response: {
			passwords: RefOf<'com.atproto.server.listAppPasswords#appPassword'>[];
		};
		errors: {
			AccountTakedown: {};
		};
	};
	/**
	 * Get a blob associated with a given account. Returns the full blob as originally uploaded. Does not require auth; implemented by PDS.
	 */
	'com.atproto.sync.getBlob': {
		params: {
			/**
			 * The DID of the account.
			 */
			did: DID;
			/**
			 * The CID of the blob to fetch
			 */
			cid: CID;
		};
		response: unknown;
	};
	/**
	 * Get data blocks from a given repo, by CID. For example, intermediate MST nodes, or records. Does not require auth; implemented by PDS.
	 */
	'com.atproto.sync.getBlocks': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
			cids: CID[];
		};
		response: unknown;
	};
	/**
	 * DEPRECATED - please use com.atproto.sync.getRepo instead
	 * @deprecated
	 */
	'com.atproto.sync.getCheckout': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
		};
		response: unknown;
	};
	/**
	 * DEPRECATED - please use com.atproto.sync.getLatestCommit instead
	 * @deprecated
	 */
	'com.atproto.sync.getHead': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
		};
		response: {
			root: CID;
		};
		errors: {
			HeadNotFound: {};
		};
	};
	/**
	 * Get the current commit CID & revision of the specified repo. Does not require auth.
	 */
	'com.atproto.sync.getLatestCommit': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
		};
		response: {
			cid: CID;
			rev: string;
		};
		errors: {
			RepoNotFound: {};
		};
	};
	/**
	 * Get data blocks needed to prove the existence or non-existence of record in the current version of repo. Does not require auth.
	 */
	'com.atproto.sync.getRecord': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
			collection: string;
			/**
			 * Record Key
			 */
			rkey: string;
			/**
			 * An optional past commit CID.
			 */
			commit?: CID;
		};
		response: unknown;
	};
	/**
	 * Download a repository export as CAR file. Optionally only a 'diff' since a previous revision. Does not require auth; implemented by PDS.
	 */
	'com.atproto.sync.getRepo': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
			/**
			 * The revision ('rev') of the repo to create a diff from.
			 */
			since?: string;
		};
		response: unknown;
	};
	/**
	 * List blob CIDso for an account, since some repo revision. Does not require auth; implemented by PDS.
	 */
	'com.atproto.sync.listBlobs': {
		params: {
			/**
			 * The DID of the repo.
			 */
			did: DID;
			/**
			 * Optional revision of the repo to list blobs since.
			 */
			since?: string;
			/**
			 * Minimum: 1 \
			 * Maximum: 1000
			 * @default 500
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			cids: CID[];
		};
	};
	/**
	 * Enumerates all the DID, rev, and commit CID for all repos hosted by this service. Does not require auth; implemented by PDS and Relay.
	 */
	'com.atproto.sync.listRepos': {
		params: {
			/**
			 * Minimum: 1 \
			 * Maximum: 1000
			 * @default 500
			 */
			limit?: number;
			cursor?: string;
		};
		response: {
			cursor?: string;
			repos: RefOf<'com.atproto.sync.listRepos#repo'>[];
		};
	};
	/**
	 * Check accounts location in signup queue.
	 */
	'com.atproto.temp.checkSignupQueue': {
		response: {
			activated: boolean;
			placeInQueue?: number;
			estimatedTimeMs?: number;
		};
	};
	/**
	 * Fetch all labels from a labeler created after a certain date. DEPRECATED: use queryLabels or subscribeLabels instead
	 */
	'com.atproto.temp.fetchLabels': {
		params: {
			since?: number;
			/**
			 * Minimum: 1 \
			 * Maximum: 250
			 * @default 50
			 */
			limit?: number;
		};
		response: {
			labels: RefOf<'com.atproto.label.defs#label'>[];
		};
	};
}

export interface Procedures {
	/**
	 * Set the private preferences attached to the account.
	 */
	'app.bsky.actor.putPreferences': {
		data: {
			preferences: RefOf<'app.bsky.actor.defs#preferences'>;
		};
	};
	/**
	 * Creates a mute relationship for the specified account. Mutes are private in Bluesky. Requires auth.
	 */
	'app.bsky.graph.muteActor': {
		data: {
			actor: string;
		};
	};
	/**
	 * Creates a mute relationship for the specified list of accounts. Mutes are private in Bluesky. Requires auth.
	 */
	'app.bsky.graph.muteActorList': {
		data: {
			list: AtUri;
		};
	};
	/**
	 * Unmutes the specified account. Requires auth.
	 */
	'app.bsky.graph.unmuteActor': {
		data: {
			actor: string;
		};
	};
	/**
	 * Unmutes the specified list of accounts. Requires auth.
	 */
	'app.bsky.graph.unmuteActorList': {
		data: {
			list: AtUri;
		};
	};
	/**
	 * Register to receive push notifications, via a specified service, for the requesting account. Requires auth.
	 */
	'app.bsky.notification.registerPush': {
		data: {
			serviceDid: DID;
			token: string;
			platform: 'ios' | 'android' | 'web' | (string & {});
			appId: string;
		};
	};
	/**
	 * Notify server that the requesting account has seen notifications. Requires auth.
	 */
	'app.bsky.notification.updateSeen': {
		data: {
			seenAt: string;
		};
	};
	/**
	 * Administrative action to create a new, re-usable communication (email for now) template.
	 */
	'com.atproto.admin.createCommunicationTemplate': {
		data: {
			/**
			 * Name of the template.
			 */
			name: string;
			/**
			 * Content of the template, markdown supported, can contain variable placeholders.
			 */
			contentMarkdown: string;
			/**
			 * Subject of the message, used in emails.
			 */
			subject: string;
			/**
			 * DID of the user who is creating the template.
			 */
			createdBy?: DID;
		};
		response: RefOf<'com.atproto.admin.defs#communicationTemplateView'>;
	};
	/**
	 * Delete a user account as an administrator.
	 */
	'com.atproto.admin.deleteAccount': {
		data: {
			did: DID;
		};
	};
	/**
	 * Delete a communication template.
	 */
	'com.atproto.admin.deleteCommunicationTemplate': {
		data: {
			id: string;
		};
	};
	/**
	 * Disable an account from receiving new invite codes, but does not invalidate existing codes.
	 */
	'com.atproto.admin.disableAccountInvites': {
		data: {
			account: DID;
			/**
			 * Optional reason for disabled invites.
			 */
			note?: string;
		};
	};
	/**
	 * Disable some set of codes and/or all codes associated with a set of users.
	 */
	'com.atproto.admin.disableInviteCodes': {
		data: {
			codes?: string[];
			accounts?: string[];
		};
	};
	/**
	 * Take a moderation action on an actor.
	 */
	'com.atproto.admin.emitModerationEvent': {
		data: {
			event:
				| UnionOf<'com.atproto.admin.defs#modEventTakedown'>
				| UnionOf<'com.atproto.admin.defs#modEventAcknowledge'>
				| UnionOf<'com.atproto.admin.defs#modEventEscalate'>
				| UnionOf<'com.atproto.admin.defs#modEventComment'>
				| UnionOf<'com.atproto.admin.defs#modEventLabel'>
				| UnionOf<'com.atproto.admin.defs#modEventReport'>
				| UnionOf<'com.atproto.admin.defs#modEventMute'>
				| UnionOf<'com.atproto.admin.defs#modEventReverseTakedown'>
				| UnionOf<'com.atproto.admin.defs#modEventUnmute'>
				| UnionOf<'com.atproto.admin.defs#modEventEmail'>
				| UnionOf<'com.atproto.admin.defs#modEventTag'>;
			subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
			subjectBlobCids?: CID[];
			createdBy: DID;
		};
		response: RefOf<'com.atproto.admin.defs#modEventView'>;
		errors: {
			SubjectHasAction: {};
		};
	};
	/**
	 * Re-enable an account's ability to receive invite codes.
	 */
	'com.atproto.admin.enableAccountInvites': {
		data: {
			account: DID;
			/**
			 * Optional reason for enabled invites.
			 */
			note?: string;
		};
	};
	/**
	 * Send email to a user's account email address.
	 */
	'com.atproto.admin.sendEmail': {
		data: {
			recipientDid: DID;
			content: string;
			subject?: string;
			senderDid: DID;
			/**
			 * Additional comment by the sender that won't be used in the email itself but helpful to provide more context for moderators/reviewers
			 */
			comment?: string;
		};
		response: {
			sent: boolean;
		};
	};
	/**
	 * Administrative action to update an account's email.
	 */
	'com.atproto.admin.updateAccountEmail': {
		data: {
			/**
			 * The handle or DID of the repo.
			 */
			account: string;
			email: string;
		};
	};
	/**
	 * Administrative action to update an account's handle.
	 */
	'com.atproto.admin.updateAccountHandle': {
		data: {
			did: DID;
			handle: Handle;
		};
	};
	/**
	 * Administrative action to update an existing communication template. Allows passing partial fields to patch specific fields only.
	 */
	'com.atproto.admin.updateCommunicationTemplate': {
		data: {
			/**
			 * ID of the template to be updated.
			 */
			id: string;
			/**
			 * Name of the template.
			 */
			name?: string;
			/**
			 * Content of the template, markdown supported, can contain variable placeholders.
			 */
			contentMarkdown?: string;
			/**
			 * Subject of the message, used in emails.
			 */
			subject?: string;
			/**
			 * DID of the user who is updating the template.
			 */
			updatedBy?: DID;
			disabled?: boolean;
		};
		response: RefOf<'com.atproto.admin.defs#communicationTemplateView'>;
	};
	/**
	 * Update the service-specific admin status of a subject (account, record, or blob).
	 */
	'com.atproto.admin.updateSubjectStatus': {
		data: {
			subject:
				| UnionOf<'com.atproto.admin.defs#repoRef'>
				| UnionOf<'com.atproto.repo.strongRef'>
				| UnionOf<'com.atproto.admin.defs#repoBlobRef'>;
			takedown?: RefOf<'com.atproto.admin.defs#statusAttr'>;
		};
		response: {
			subject:
				| UnionOf<'com.atproto.admin.defs#repoRef'>
				| UnionOf<'com.atproto.repo.strongRef'>
				| UnionOf<'com.atproto.admin.defs#repoBlobRef'>;
			takedown?: RefOf<'com.atproto.admin.defs#statusAttr'>;
		};
	};
	/**
	 * Request an email with a code to in order to request a signed PLC operation. Requires Auth.
	 */
	'com.atproto.identity.requestPlcOperationSignature': {};
	/**
	 * Signs a PLC operation to update some value(s) in the requesting DID's document.
	 */
	'com.atproto.identity.signPlcOperation': {
		data: {
			/**
			 * A token received through com.atproto.identity.requestPlcOperationSignature
			 */
			token?: string;
			rotationKeys?: string[];
			alsoKnownAs?: string[];
			verificationMethods?: unknown;
			services?: unknown;
		};
		response: {
			/**
			 * A signed DID PLC operation.
			 */
			operation: unknown;
		};
	};
	/**
	 * Validates a PLC operation to ensure that it doesn't violate a service's constraints or get the identity into a bad state, then submits it to the PLC registry
	 */
	'com.atproto.identity.submitPlcOperation': {
		data: {
			operation: unknown;
		};
	};
	/**
	 * Updates the current account's handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
	 */
	'com.atproto.identity.updateHandle': {
		data: {
			/**
			 * The new handle.
			 */
			handle: Handle;
		};
	};
	/**
	 * Submit a moderation report regarding an atproto account or record. Implemented by moderation services (with PDS proxying), and requires auth.
	 */
	'com.atproto.moderation.createReport': {
		data: {
			/**
			 * Indicates the broad category of violation the report is for.
			 */
			reasonType: RefOf<'com.atproto.moderation.defs#reasonType'>;
			/**
			 * Additional context about the content and violation.
			 */
			reason?: string;
			subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
		};
		response: {
			id: number;
			reasonType: RefOf<'com.atproto.moderation.defs#reasonType'>;
			/**
			 * Maximum string length: 20000 \
			 * Maximum grapheme length: 2000
			 */
			reason?: string;
			subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
			reportedBy: DID;
			createdAt: string;
		};
	};
	/**
	 * Apply a batch transaction of repository creates, updates, and deletes. Requires auth, implemented by PDS.
	 */
	'com.atproto.repo.applyWrites': {
		data: {
			/**
			 * The handle or DID of the repo (aka, current account).
			 */
			repo: string;
			/**
			 * Can be set to 'false' to skip Lexicon schema validation of record data, for all operations.
			 * @default true
			 */
			validate?: boolean;
			writes: (
				| UnionOf<'com.atproto.repo.applyWrites#create'>
				| UnionOf<'com.atproto.repo.applyWrites#update'>
				| UnionOf<'com.atproto.repo.applyWrites#delete'>
			)[];
			/**
			 * If provided, the entire operation will fail if the current repo commit CID does not match this value. Used to prevent conflicting repo mutations.
			 */
			swapCommit?: CID;
		};
		errors: {
			InvalidSwap: {};
		};
	};
	/**
	 * Create a single new repository record. Requires auth, implemented by PDS.
	 */
	'com.atproto.repo.createRecord': {
		data: {
			/**
			 * The handle or DID of the repo (aka, current account).
			 */
			repo: string;
			/**
			 * The NSID of the record collection.
			 */
			collection: string;
			/**
			 * The Record Key. \
			 * Maximum string length: 15
			 */
			rkey?: string;
			/**
			 * Can be set to 'false' to skip Lexicon schema validation of record data.
			 * @default true
			 */
			validate?: boolean;
			/**
			 * The record itself. Must contain a $type field.
			 */
			record: unknown;
			/**
			 * Compare and swap with the previous commit by CID.
			 */
			swapCommit?: CID;
		};
		response: {
			uri: AtUri;
			cid: CID;
		};
		errors: {
			InvalidSwap: {};
		};
	};
	/**
	 * Delete a repository record, or ensure it doesn't exist. Requires auth, implemented by PDS.
	 */
	'com.atproto.repo.deleteRecord': {
		data: {
			/**
			 * The handle or DID of the repo (aka, current account).
			 */
			repo: string;
			/**
			 * The NSID of the record collection.
			 */
			collection: string;
			/**
			 * The Record Key.
			 */
			rkey: string;
			/**
			 * Compare and swap with the previous record by CID.
			 */
			swapRecord?: CID;
			/**
			 * Compare and swap with the previous commit by CID.
			 */
			swapCommit?: CID;
		};
		errors: {
			InvalidSwap: {};
		};
	};
	/**
	 * Import a repo in the form of a CAR file. Requires Content-Length HTTP header to be set.
	 */
	'com.atproto.repo.importRepo': {
		data: Blob;
	};
	/**
	 * Write a repository record, creating or updating it as needed. Requires auth, implemented by PDS.
	 */
	'com.atproto.repo.putRecord': {
		data: {
			/**
			 * The handle or DID of the repo (aka, current account).
			 */
			repo: string;
			/**
			 * The NSID of the record collection.
			 */
			collection: string;
			/**
			 * The Record Key. \
			 * Maximum string length: 15
			 */
			rkey: string;
			/**
			 * Can be set to 'false' to skip Lexicon schema validation of record data.
			 * @default true
			 */
			validate?: boolean;
			/**
			 * The record to write.
			 */
			record: unknown;
			/**
			 * Compare and swap with the previous record by CID. WARNING: nullable and optional field; may cause problems with golang implementation
			 */
			swapRecord?: CID;
			/**
			 * Compare and swap with the previous commit by CID.
			 */
			swapCommit?: CID;
		};
		response: {
			uri: AtUri;
			cid: CID;
		};
		errors: {
			InvalidSwap: {};
		};
	};
	/**
	 * Upload a new blob, to be referenced from a repository record. The blob will be deleted if it is not referenced within a time window (eg, minutes). Blob restrictions (mimetype, size, etc) are enforced when the reference is created. Requires auth, implemented by PDS.
	 */
	'com.atproto.repo.uploadBlob': {
		data: Blob;
		response: {
			blob: AtBlob;
		};
	};
	/**
	 * Activates a currently deactivated account. Used to finalize account migration after the account's repo is imported and identity is setup.
	 */
	'com.atproto.server.activateAccount': {};
	/**
	 * Confirm an email using a token from com.atproto.server.requestEmailConfirmation.
	 */
	'com.atproto.server.confirmEmail': {
		data: {
			email: string;
			token: string;
		};
		errors: {
			AccountNotFound: {};
			ExpiredToken: {};
			InvalidToken: {};
			InvalidEmail: {};
		};
	};
	/**
	 * Create an account. Implemented by PDS.
	 */
	'com.atproto.server.createAccount': {
		data: {
			email?: string;
			/**
			 * Requested handle for the account.
			 */
			handle: Handle;
			/**
			 * Pre-existing atproto DID, being imported to a new account.
			 */
			did?: DID;
			inviteCode?: string;
			verificationCode?: string;
			verificationPhone?: string;
			/**
			 * Initial account password. May need to meet instance-specific password strength requirements.
			 */
			password?: string;
			/**
			 * DID PLC rotation key (aka, recovery key) to be included in PLC creation operation.
			 */
			recoveryKey?: string;
			/**
			 * A signed DID PLC operation to be submitted as part of importing an existing account to this instance. NOTE: this optional field may be updated when full account migration is implemented.
			 */
			plcOp?: unknown;
		};
		/**
		 * Account login session returned on successful account creation.
		 */
		response: {
			accessJwt: string;
			refreshJwt: string;
			handle: Handle;
			/**
			 * The DID of the new account.
			 */
			did: DID;
			/**
			 * Complete DID document.
			 */
			didDoc?: unknown;
		};
		errors: {
			InvalidHandle: {};
			InvalidPassword: {};
			InvalidInviteCode: {};
			HandleNotAvailable: {};
			UnsupportedDomain: {};
			UnresolvableDid: {};
			IncompatibleDidDoc: {};
		};
	};
	/**
	 * Create an App Password.
	 */
	'com.atproto.server.createAppPassword': {
		data: {
			/**
			 * A short name for the App Password, to help distinguish them.
			 */
			name: string;
		};
		response: RefOf<'com.atproto.server.createAppPassword#appPassword'>;
		errors: {
			AccountTakedown: {};
		};
	};
	/**
	 * Create an invite code.
	 */
	'com.atproto.server.createInviteCode': {
		data: {
			useCount: number;
			forAccount?: DID;
		};
		response: {
			code: string;
		};
	};
	/**
	 * Create invite codes.
	 */
	'com.atproto.server.createInviteCodes': {
		data: {
			/**
			 * @default 1
			 */
			codeCount: number;
			useCount: number;
			forAccounts?: DID[];
		};
		response: {
			codes: RefOf<'com.atproto.server.createInviteCodes#accountCodes'>[];
		};
	};
	/**
	 * Create an authentication session.
	 */
	'com.atproto.server.createSession': {
		data: {
			/**
			 * Handle or other identifier supported by the server for the authenticating user.
			 */
			identifier: string;
			password: string;
		};
		response: {
			accessJwt: string;
			refreshJwt: string;
			handle: Handle;
			did: DID;
			didDoc?: unknown;
			email?: string;
			emailConfirmed?: boolean;
		};
		errors: {
			AccountTakedown: {};
		};
	};
	/**
	 * Deactivates a currently active account. Stops serving of repo, and future writes to repo until reactivated. Used to finalize account migration with the old host after the account has been activated on the new host.
	 */
	'com.atproto.server.deactivateAccount': {
		data: {
			/**
			 * A recommendation to server as to how long they should hold onto the deactivated account before deleting.
			 */
			deleteAfter?: string;
		};
	};
	/**
	 * Delete an actor's account with a token and password. Can only be called after requesting a deletion token. Requires auth.
	 */
	'com.atproto.server.deleteAccount': {
		data: {
			did: DID;
			password: string;
			token: string;
		};
		errors: {
			ExpiredToken: {};
			InvalidToken: {};
		};
	};
	/**
	 * Delete the current session. Requires auth.
	 */
	'com.atproto.server.deleteSession': {};
	/**
	 * Refresh an authentication session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
	 */
	'com.atproto.server.refreshSession': {
		response: {
			accessJwt: string;
			refreshJwt: string;
			handle: Handle;
			did: DID;
			didDoc?: unknown;
		};
		errors: {
			AccountTakedown: {};
		};
	};
	/**
	 * Initiate a user account deletion via email.
	 */
	'com.atproto.server.requestAccountDelete': {};
	/**
	 * Request an email with a code to confirm ownership of email.
	 */
	'com.atproto.server.requestEmailConfirmation': {};
	/**
	 * Request a token in order to update email.
	 */
	'com.atproto.server.requestEmailUpdate': {
		response: {
			tokenRequired: boolean;
		};
	};
	/**
	 * Initiate a user account password reset via email.
	 */
	'com.atproto.server.requestPasswordReset': {
		data: {
			email: string;
		};
	};
	/**
	 * Reserve a repo signing key, for use with account creation. Necessary so that a DID PLC update operation can be constructed during an account migraiton. Public and does not require auth; implemented by PDS. NOTE: this endpoint may change when full account migration is implemented.
	 */
	'com.atproto.server.reserveSigningKey': {
		data: {
			/**
			 * The DID to reserve a key for.
			 */
			did?: DID;
		};
		response: {
			/**
			 * The public key for the reserved signing key, in did:key serialization.
			 */
			signingKey: string;
		};
	};
	/**
	 * Reset a user account password using a token.
	 */
	'com.atproto.server.resetPassword': {
		data: {
			token: string;
			password: string;
		};
		errors: {
			ExpiredToken: {};
			InvalidToken: {};
		};
	};
	/**
	 * Revoke an App Password by name.
	 */
	'com.atproto.server.revokeAppPassword': {
		data: {
			name: string;
		};
	};
	/**
	 * Update an account's email.
	 */
	'com.atproto.server.updateEmail': {
		data: {
			email: string;
			/**
			 * Requires a token from com.atproto.sever.requestEmailUpdate if the account's email has been confirmed.
			 */
			token?: string;
		};
		errors: {
			ExpiredToken: {};
			InvalidToken: {};
			TokenRequired: {};
		};
	};
	/**
	 * Notify a crawling service of a recent update, and that crawling should resume. Intended use is after a gap between repo stream events caused the crawling service to disconnect. Does not require auth; implemented by Relay.
	 */
	'com.atproto.sync.notifyOfUpdate': {
		data: {
			/**
			 * Hostname of the current service (usually a PDS) that is notifying of update.
			 */
			hostname: string;
		};
	};
	/**
	 * Request a service to persistently crawl hosted repos. Expected use is new PDS instances declaring their existence to Relays. Does not require auth.
	 */
	'com.atproto.sync.requestCrawl': {
		data: {
			/**
			 * Hostname of the current service (eg, PDS) that is requesting to be crawled.
			 */
			hostname: string;
		};
	};
	/**
	 * Request a verification code to be sent to the supplied phone number
	 */
	'com.atproto.temp.requestPhoneVerification': {
		data: {
			phoneNumber: string;
		};
	};
}

export interface Subscriptions {}

export interface Objects {
	'app.bsky.actor.defs#profileViewBasic': {
		did: DID;
		handle: Handle;
		/**
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		displayName?: string;
		avatar?: string;
		viewer?: RefOf<'app.bsky.actor.defs#viewerState'>;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
	};
	'app.bsky.actor.defs#profileView': {
		did: DID;
		handle: Handle;
		/**
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		displayName?: string;
		/**
		 * Maximum string length: 2560 \
		 * Maximum grapheme length: 256
		 */
		description?: string;
		avatar?: string;
		indexedAt?: string;
		viewer?: RefOf<'app.bsky.actor.defs#viewerState'>;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
	};
	'app.bsky.actor.defs#profileViewDetailed': {
		did: DID;
		handle: Handle;
		/**
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		displayName?: string;
		/**
		 * Maximum string length: 2560 \
		 * Maximum grapheme length: 256
		 */
		description?: string;
		avatar?: string;
		banner?: string;
		followersCount?: number;
		followsCount?: number;
		postsCount?: number;
		indexedAt?: string;
		viewer?: RefOf<'app.bsky.actor.defs#viewerState'>;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
	};
	/**
	 * Metadata about the requesting account's relationship with the subject account. Only has meaningful content for authed requests.
	 */
	'app.bsky.actor.defs#viewerState': {
		muted?: boolean;
		mutedByList?: RefOf<'app.bsky.graph.defs#listViewBasic'>;
		blockedBy?: boolean;
		blocking?: AtUri;
		blockingByList?: RefOf<'app.bsky.graph.defs#listViewBasic'>;
		following?: AtUri;
		followedBy?: AtUri;
	};
	'app.bsky.actor.defs#preferences': (
		| UnionOf<'app.bsky.actor.defs#adultContentPref'>
		| UnionOf<'app.bsky.actor.defs#contentLabelPref'>
		| UnionOf<'app.bsky.actor.defs#savedFeedsPref'>
		| UnionOf<'app.bsky.actor.defs#personalDetailsPref'>
		| UnionOf<'app.bsky.actor.defs#feedViewPref'>
		| UnionOf<'app.bsky.actor.defs#threadViewPref'>
		| UnionOf<'app.bsky.actor.defs#interestsPref'>
	)[];
	'app.bsky.actor.defs#adultContentPref': {
		/**
		 * @default false
		 */
		enabled: boolean;
	};
	'app.bsky.actor.defs#contentLabelPref': {
		label: string;
		visibility: 'show' | 'warn' | 'hide' | (string & {});
	};
	'app.bsky.actor.defs#savedFeedsPref': {
		pinned: AtUri[];
		saved: AtUri[];
		timelineIndex?: number;
	};
	'app.bsky.actor.defs#personalDetailsPref': {
		/**
		 * The birth date of account owner.
		 */
		birthDate?: string;
	};
	'app.bsky.actor.defs#feedViewPref': {
		/**
		 * The URI of the feed, or an identifier which describes the feed.
		 */
		feed: string;
		/**
		 * Hide replies in the feed.
		 */
		hideReplies?: boolean;
		/**
		 * Hide replies in the feed if they are not by followed users.
		 */
		hideRepliesByUnfollowed?: boolean;
		/**
		 * Hide replies in the feed if they do not have this number of likes.
		 */
		hideRepliesByLikeCount?: number;
		/**
		 * Hide reposts in the feed.
		 */
		hideReposts?: boolean;
		/**
		 * Hide quote posts in the feed.
		 */
		hideQuotePosts?: boolean;
	};
	'app.bsky.actor.defs#threadViewPref': {
		/**
		 * Sorting mode for threads.
		 */
		sort?: 'oldest' | 'newest' | 'most-likes' | 'random' | (string & {});
		/**
		 * Show followed users at the top of all replies.
		 */
		prioritizeFollowedUsers?: boolean;
	};
	'app.bsky.actor.defs#interestsPref': {
		/**
		 * A list of tags which describe the account owner's interests gathered during onboarding. \
		 * Maximum array length: 100 \
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		tags: string[];
	};
	/**
	 * Maximum string length: 640 \
	 * Maximum grapheme length: 64
	 */
	'app.bsky.actor.defs#mutedWordTarget': 'content' | 'tag' | (string & {});
	/**
	 * A word that the account owner has muted.
	 */
	'app.bsky.actor.defs#mutedWord': {
		/**
		 * The muted word itself. \
		 * Maximum string length: 10000 \
		 * Maximum grapheme length: 1000
		 */
		value: string;
		/**
		 * The intended targets of the muted word.
		 */
		targets: RefOf<'app.bsky.actor.defs#mutedWordTarget'>[];
	};
	'app.bsky.actor.defs#mutedWordsPref': {
		/**
		 * A list of words the account owner has muted.
		 */
		items: RefOf<'app.bsky.actor.defs#mutedWord'>[];
	};
	'app.bsky.actor.defs#hiddenPostsPref': {
		/**
		 * A list of URIs of posts the account owner has hidden.
		 */
		items: AtUri[];
	};
	/**
	 * A representation of some externally linked content (eg, a URL and 'card'), embedded in a Bluesky record (eg, a post).
	 */
	'app.bsky.embed.external': {
		external: RefOf<'app.bsky.embed.external#external'>;
	};
	'app.bsky.embed.external#external': {
		uri: string;
		title: string;
		description: string;
		thumb?: AtBlob<`image/${string}`>;
	};
	'app.bsky.embed.external#view': {
		external: RefOf<'app.bsky.embed.external#viewExternal'>;
	};
	'app.bsky.embed.external#viewExternal': {
		uri: string;
		title: string;
		description: string;
		thumb?: string;
	};
	'app.bsky.embed.images': {
		/**
		 * Maximum array length: 4
		 */
		images: RefOf<'app.bsky.embed.images#image'>[];
	};
	'app.bsky.embed.images#image': {
		image: AtBlob<`image/${string}`>;
		/**
		 * Alt text description of the image, for accessibility.
		 */
		alt: string;
		aspectRatio?: RefOf<'app.bsky.embed.images#aspectRatio'>;
	};
	/**
	 * width:height represents an aspect ratio. It may be approximate, and may not correspond to absolute dimensions in any given unit.
	 */
	'app.bsky.embed.images#aspectRatio': {
		/**
		 * Minimum: 1
		 */
		width: number;
		/**
		 * Minimum: 1
		 */
		height: number;
	};
	'app.bsky.embed.images#view': {
		/**
		 * Maximum array length: 4
		 */
		images: RefOf<'app.bsky.embed.images#viewImage'>[];
	};
	'app.bsky.embed.images#viewImage': {
		/**
		 * Fully-qualified URL where a thumbnail of the image can be fetched. For example, CDN location provided by the App View.
		 */
		thumb: string;
		/**
		 * Fully-qualified URL where a large version of the image can be fetched. May or may not be the exact original blob. For example, CDN location provided by the App View.
		 */
		fullsize: string;
		/**
		 * Alt text description of the image, for accessibility.
		 */
		alt: string;
		aspectRatio?: RefOf<'app.bsky.embed.images#aspectRatio'>;
	};
	'app.bsky.embed.record': {
		record: RefOf<'com.atproto.repo.strongRef'>;
	};
	'app.bsky.embed.record#view': {
		record:
			| UnionOf<'app.bsky.embed.record#viewRecord'>
			| UnionOf<'app.bsky.embed.record#viewNotFound'>
			| UnionOf<'app.bsky.embed.record#viewBlocked'>
			| UnionOf<'app.bsky.feed.defs#generatorView'>
			| UnionOf<'app.bsky.graph.defs#listView'>;
	};
	'app.bsky.embed.record#viewRecord': {
		uri: AtUri;
		cid: CID;
		author: RefOf<'app.bsky.actor.defs#profileViewBasic'>;
		/**
		 * The record data itself.
		 */
		value: unknown;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
		embeds?: (
			| UnionOf<'app.bsky.embed.images#view'>
			| UnionOf<'app.bsky.embed.external#view'>
			| UnionOf<'app.bsky.embed.record#view'>
			| UnionOf<'app.bsky.embed.recordWithMedia#view'>
		)[];
		indexedAt: string;
	};
	'app.bsky.embed.record#viewNotFound': {
		uri: AtUri;
		notFound: boolean;
	};
	'app.bsky.embed.record#viewBlocked': {
		uri: AtUri;
		blocked: boolean;
		author: RefOf<'app.bsky.feed.defs#blockedAuthor'>;
	};
	'app.bsky.embed.recordWithMedia': {
		record: RefOf<'app.bsky.embed.record'>;
		media: UnionOf<'app.bsky.embed.images'> | UnionOf<'app.bsky.embed.external'>;
	};
	'app.bsky.embed.recordWithMedia#view': {
		record: RefOf<'app.bsky.embed.record#view'>;
		media: UnionOf<'app.bsky.embed.images#view'> | UnionOf<'app.bsky.embed.external#view'>;
	};
	'app.bsky.feed.defs#postView': {
		uri: AtUri;
		cid: CID;
		author: RefOf<'app.bsky.actor.defs#profileViewBasic'>;
		record: unknown;
		embed?:
			| UnionOf<'app.bsky.embed.images#view'>
			| UnionOf<'app.bsky.embed.external#view'>
			| UnionOf<'app.bsky.embed.record#view'>
			| UnionOf<'app.bsky.embed.recordWithMedia#view'>;
		replyCount?: number;
		repostCount?: number;
		likeCount?: number;
		indexedAt: string;
		viewer?: RefOf<'app.bsky.feed.defs#viewerState'>;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
		threadgate?: RefOf<'app.bsky.feed.defs#threadgateView'>;
	};
	/**
	 * Metadata about the requesting account's relationship with the subject content. Only has meaningful content for authed requests.
	 */
	'app.bsky.feed.defs#viewerState': {
		repost?: AtUri;
		like?: AtUri;
		replyDisabled?: boolean;
	};
	'app.bsky.feed.defs#feedViewPost': {
		post: RefOf<'app.bsky.feed.defs#postView'>;
		reply?: RefOf<'app.bsky.feed.defs#replyRef'>;
		reason?: UnionOf<'app.bsky.feed.defs#reasonRepost'>;
	};
	'app.bsky.feed.defs#replyRef': {
		root:
			| UnionOf<'app.bsky.feed.defs#postView'>
			| UnionOf<'app.bsky.feed.defs#notFoundPost'>
			| UnionOf<'app.bsky.feed.defs#blockedPost'>;
		parent:
			| UnionOf<'app.bsky.feed.defs#postView'>
			| UnionOf<'app.bsky.feed.defs#notFoundPost'>
			| UnionOf<'app.bsky.feed.defs#blockedPost'>;
	};
	'app.bsky.feed.defs#reasonRepost': {
		by: RefOf<'app.bsky.actor.defs#profileViewBasic'>;
		indexedAt: string;
	};
	'app.bsky.feed.defs#threadViewPost': {
		post: RefOf<'app.bsky.feed.defs#postView'>;
		parent?:
			| UnionOf<'app.bsky.feed.defs#threadViewPost'>
			| UnionOf<'app.bsky.feed.defs#notFoundPost'>
			| UnionOf<'app.bsky.feed.defs#blockedPost'>;
		replies?: (
			| UnionOf<'app.bsky.feed.defs#threadViewPost'>
			| UnionOf<'app.bsky.feed.defs#notFoundPost'>
			| UnionOf<'app.bsky.feed.defs#blockedPost'>
		)[];
	};
	'app.bsky.feed.defs#notFoundPost': {
		uri: AtUri;
		notFound: boolean;
	};
	'app.bsky.feed.defs#blockedPost': {
		uri: AtUri;
		blocked: boolean;
		author: RefOf<'app.bsky.feed.defs#blockedAuthor'>;
	};
	'app.bsky.feed.defs#blockedAuthor': {
		did: DID;
		viewer?: RefOf<'app.bsky.actor.defs#viewerState'>;
	};
	'app.bsky.feed.defs#generatorView': {
		uri: AtUri;
		cid: CID;
		did: DID;
		creator: RefOf<'app.bsky.actor.defs#profileView'>;
		displayName: string;
		/**
		 * Maximum string length: 3000 \
		 * Maximum grapheme length: 300
		 */
		description?: string;
		descriptionFacets?: RefOf<'app.bsky.richtext.facet'>[];
		avatar?: string;
		/**
		 * Minimum: 0
		 */
		likeCount?: number;
		viewer?: RefOf<'app.bsky.feed.defs#generatorViewerState'>;
		indexedAt: string;
	};
	'app.bsky.feed.defs#generatorViewerState': {
		like?: AtUri;
	};
	'app.bsky.feed.defs#skeletonFeedPost': {
		post: AtUri;
		reason?: UnionOf<'app.bsky.feed.defs#skeletonReasonRepost'>;
	};
	'app.bsky.feed.defs#skeletonReasonRepost': {
		repost: AtUri;
	};
	'app.bsky.feed.defs#threadgateView': {
		uri?: AtUri;
		cid?: CID;
		record?: unknown;
		lists?: RefOf<'app.bsky.graph.defs#listViewBasic'>[];
	};
	'app.bsky.feed.describeFeedGenerator#feed': {
		uri: AtUri;
	};
	'app.bsky.feed.describeFeedGenerator#links': {
		privacyPolicy?: string;
		termsOfService?: string;
	};
	'app.bsky.feed.getLikes#like': {
		indexedAt: string;
		createdAt: string;
		actor: RefOf<'app.bsky.actor.defs#profileView'>;
	};
	'app.bsky.feed.post#replyRef': {
		root: RefOf<'com.atproto.repo.strongRef'>;
		parent: RefOf<'com.atproto.repo.strongRef'>;
	};
	/**
	 * Deprecated: use facets instead.
	 * @deprecated
	 */
	'app.bsky.feed.post#entity': {
		index: RefOf<'app.bsky.feed.post#textSlice'>;
		/**
		 * Expected values are 'mention' and 'link'.
		 */
		type: string;
		value: string;
	};
	/**
	 * Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.
	 * @deprecated
	 */
	'app.bsky.feed.post#textSlice': {
		/**
		 * Minimum: 0
		 */
		start: number;
		/**
		 * Minimum: 0
		 */
		end: number;
	};
	/**
	 * Allow replies from actors mentioned in your post.
	 */
	'app.bsky.feed.threadgate#mentionRule': {};
	/**
	 * Allow replies from actors you follow.
	 */
	'app.bsky.feed.threadgate#followingRule': {};
	/**
	 * Allow replies from actors on a list.
	 */
	'app.bsky.feed.threadgate#listRule': {
		list: AtUri;
	};
	'app.bsky.graph.defs#listViewBasic': {
		uri: AtUri;
		cid: CID;
		/**
		 * Minimum string length: 1 \
		 * Maximum string length: 64
		 */
		name: string;
		purpose: RefOf<'app.bsky.graph.defs#listPurpose'>;
		avatar?: string;
		viewer?: RefOf<'app.bsky.graph.defs#listViewerState'>;
		indexedAt?: string;
	};
	'app.bsky.graph.defs#listView': {
		uri: AtUri;
		cid: CID;
		creator: RefOf<'app.bsky.actor.defs#profileView'>;
		/**
		 * Minimum string length: 1 \
		 * Maximum string length: 64
		 */
		name: string;
		purpose: RefOf<'app.bsky.graph.defs#listPurpose'>;
		/**
		 * Maximum string length: 3000 \
		 * Maximum grapheme length: 300
		 */
		description?: string;
		descriptionFacets?: RefOf<'app.bsky.richtext.facet'>[];
		avatar?: string;
		viewer?: RefOf<'app.bsky.graph.defs#listViewerState'>;
		indexedAt: string;
	};
	'app.bsky.graph.defs#listItemView': {
		uri: AtUri;
		subject: RefOf<'app.bsky.actor.defs#profileView'>;
	};
	'app.bsky.graph.defs#listPurpose':
		| 'app.bsky.graph.defs#modlist'
		| 'app.bsky.graph.defs#curatelist'
		| (string & {});
	'app.bsky.graph.defs#modlist': 'app.bsky.graph.defs#modlist';
	'app.bsky.graph.defs#curatelist': 'app.bsky.graph.defs#curatelist';
	'app.bsky.graph.defs#listViewerState': {
		muted?: boolean;
		blocked?: AtUri;
	};
	/**
	 * indicates that a handle or DID could not be resolved
	 */
	'app.bsky.graph.defs#notFoundActor': {
		actor: string;
		notFound: boolean;
	};
	/**
	 * lists the bi-directional graph relationships between one actor (not indicated in the object), and the target actors (the DID included in the object)
	 */
	'app.bsky.graph.defs#relationship': {
		did: DID;
		/**
		 * if the actor follows this DID, this is the AT-URI of the follow record
		 */
		following?: AtUri;
		/**
		 * if the actor is followed by this DID, contains the AT-URI of the follow record
		 */
		followedBy?: AtUri;
	};
	'app.bsky.notification.listNotifications#notification': {
		uri: AtUri;
		cid: CID;
		author: RefOf<'app.bsky.actor.defs#profileView'>;
		/**
		 * Expected values are 'like', 'repost', 'follow', 'mention', 'reply', and 'quote'.
		 */
		reason: 'like' | 'repost' | 'follow' | 'mention' | 'reply' | 'quote' | (string & {});
		reasonSubject?: AtUri;
		record: unknown;
		isRead: boolean;
		indexedAt: string;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
	};
	/**
	 * Annotation of a sub-string within rich text.
	 */
	'app.bsky.richtext.facet': {
		index: RefOf<'app.bsky.richtext.facet#byteSlice'>;
		features: (
			| UnionOf<'app.bsky.richtext.facet#mention'>
			| UnionOf<'app.bsky.richtext.facet#link'>
			| UnionOf<'app.bsky.richtext.facet#tag'>
		)[];
	};
	/**
	 * Facet feature for mention of another account. The text is usually a handle, including a '@' prefix, but the facet reference is a DID.
	 */
	'app.bsky.richtext.facet#mention': {
		did: DID;
	};
	/**
	 * Facet feature for a URL. The text URL may have been simplified or truncated, but the facet reference should be a complete URL.
	 */
	'app.bsky.richtext.facet#link': {
		uri: string;
	};
	/**
	 * Facet feature for a hashtag. The text usually includes a '#' prefix, but the facet reference should not (except in the case of 'double hash tags').
	 */
	'app.bsky.richtext.facet#tag': {
		/**
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		tag: string;
	};
	/**
	 * Specifies the sub-string range a facet feature applies to. Start index is inclusive, end index is exclusive. Indices are zero-indexed, counting bytes of the UTF-8 encoded text. NOTE: some languages, like Javascript, use UTF-16 or Unicode codepoints for string slice indexing; in these languages, convert to byte arrays before working with facets.
	 */
	'app.bsky.richtext.facet#byteSlice': {
		/**
		 * Minimum: 0
		 */
		byteStart: number;
		/**
		 * Minimum: 0
		 */
		byteEnd: number;
	};
	'app.bsky.unspecced.defs#skeletonSearchPost': {
		uri: AtUri;
	};
	'app.bsky.unspecced.defs#skeletonSearchActor': {
		did: DID;
	};
	'app.bsky.unspecced.getTaggedSuggestions#suggestion': {
		tag: string;
		subjectType: 'actor' | 'feed' | (string & {});
		subject: string;
	};
	'com.atproto.admin.defs#statusAttr': {
		applied: boolean;
		ref?: string;
	};
	'com.atproto.admin.defs#modEventView': {
		id: number;
		event:
			| UnionOf<'com.atproto.admin.defs#modEventTakedown'>
			| UnionOf<'com.atproto.admin.defs#modEventReverseTakedown'>
			| UnionOf<'com.atproto.admin.defs#modEventComment'>
			| UnionOf<'com.atproto.admin.defs#modEventReport'>
			| UnionOf<'com.atproto.admin.defs#modEventLabel'>
			| UnionOf<'com.atproto.admin.defs#modEventAcknowledge'>
			| UnionOf<'com.atproto.admin.defs#modEventEscalate'>
			| UnionOf<'com.atproto.admin.defs#modEventMute'>
			| UnionOf<'com.atproto.admin.defs#modEventEmail'>
			| UnionOf<'com.atproto.admin.defs#modEventResolveAppeal'>;
		subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
		subjectBlobCids: string[];
		createdBy: DID;
		createdAt: string;
		creatorHandle?: string;
		subjectHandle?: string;
	};
	'com.atproto.admin.defs#modEventViewDetail': {
		id: number;
		event:
			| UnionOf<'com.atproto.admin.defs#modEventTakedown'>
			| UnionOf<'com.atproto.admin.defs#modEventReverseTakedown'>
			| UnionOf<'com.atproto.admin.defs#modEventComment'>
			| UnionOf<'com.atproto.admin.defs#modEventReport'>
			| UnionOf<'com.atproto.admin.defs#modEventLabel'>
			| UnionOf<'com.atproto.admin.defs#modEventAcknowledge'>
			| UnionOf<'com.atproto.admin.defs#modEventEscalate'>
			| UnionOf<'com.atproto.admin.defs#modEventMute'>
			| UnionOf<'com.atproto.admin.defs#modEventEmail'>
			| UnionOf<'com.atproto.admin.defs#modEventResolveAppeal'>;
		subject:
			| UnionOf<'com.atproto.admin.defs#repoView'>
			| UnionOf<'com.atproto.admin.defs#repoViewNotFound'>
			| UnionOf<'com.atproto.admin.defs#recordView'>
			| UnionOf<'com.atproto.admin.defs#recordViewNotFound'>;
		subjectBlobs: RefOf<'com.atproto.admin.defs#blobView'>[];
		createdBy: DID;
		createdAt: string;
	};
	'com.atproto.admin.defs#reportView': {
		id: number;
		reasonType: RefOf<'com.atproto.moderation.defs#reasonType'>;
		comment?: string;
		subjectRepoHandle?: string;
		subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
		reportedBy: DID;
		createdAt: string;
		resolvedByActionIds: number[];
	};
	'com.atproto.admin.defs#subjectStatusView': {
		id: number;
		subject: UnionOf<'com.atproto.admin.defs#repoRef'> | UnionOf<'com.atproto.repo.strongRef'>;
		subjectBlobCids?: CID[];
		subjectRepoHandle?: string;
		/**
		 * Timestamp referencing when the last update was made to the moderation status of the subject
		 */
		updatedAt: string;
		/**
		 * Timestamp referencing the first moderation status impacting event was emitted on the subject
		 */
		createdAt: string;
		reviewState: RefOf<'com.atproto.admin.defs#subjectReviewState'>;
		/**
		 * Sticky comment on the subject.
		 */
		comment?: string;
		muteUntil?: string;
		lastReviewedBy?: DID;
		lastReviewedAt?: string;
		lastReportedAt?: string;
		/**
		 * Timestamp referencing when the author of the subject appealed a moderation action
		 */
		lastAppealedAt?: string;
		takendown?: boolean;
		/**
		 * True indicates that the a previously taken moderator action was appealed against, by the author of the content. False indicates last appeal was resolved by moderators.
		 */
		appealed?: boolean;
		suspendUntil?: string;
		tags?: string[];
	};
	'com.atproto.admin.defs#reportViewDetail': {
		id: number;
		reasonType: RefOf<'com.atproto.moderation.defs#reasonType'>;
		comment?: string;
		subject:
			| UnionOf<'com.atproto.admin.defs#repoView'>
			| UnionOf<'com.atproto.admin.defs#repoViewNotFound'>
			| UnionOf<'com.atproto.admin.defs#recordView'>
			| UnionOf<'com.atproto.admin.defs#recordViewNotFound'>;
		subjectStatus?: RefOf<'com.atproto.admin.defs#subjectStatusView'>;
		reportedBy: DID;
		createdAt: string;
		resolvedByActions: RefOf<'com.atproto.admin.defs#modEventView'>[];
	};
	'com.atproto.admin.defs#repoView': {
		did: DID;
		handle: Handle;
		email?: string;
		relatedRecords: unknown[];
		indexedAt: string;
		moderation: RefOf<'com.atproto.admin.defs#moderation'>;
		invitedBy?: RefOf<'com.atproto.server.defs#inviteCode'>;
		invitesDisabled?: boolean;
		inviteNote?: string;
	};
	'com.atproto.admin.defs#repoViewDetail': {
		did: DID;
		handle: Handle;
		email?: string;
		relatedRecords: unknown[];
		indexedAt: string;
		moderation: RefOf<'com.atproto.admin.defs#moderationDetail'>;
		labels?: RefOf<'com.atproto.label.defs#label'>[];
		invitedBy?: RefOf<'com.atproto.server.defs#inviteCode'>;
		invites?: RefOf<'com.atproto.server.defs#inviteCode'>[];
		invitesDisabled?: boolean;
		inviteNote?: string;
		emailConfirmedAt?: string;
	};
	'com.atproto.admin.defs#accountView': {
		did: DID;
		handle: Handle;
		email?: string;
		relatedRecords?: unknown[];
		indexedAt: string;
		invitedBy?: RefOf<'com.atproto.server.defs#inviteCode'>;
		invites?: RefOf<'com.atproto.server.defs#inviteCode'>[];
		invitesDisabled?: boolean;
		emailConfirmedAt?: string;
		inviteNote?: string;
	};
	'com.atproto.admin.defs#repoViewNotFound': {
		did: DID;
	};
	'com.atproto.admin.defs#repoRef': {
		did: DID;
	};
	'com.atproto.admin.defs#repoBlobRef': {
		did: DID;
		cid: CID;
		recordUri?: AtUri;
	};
	'com.atproto.admin.defs#recordView': {
		uri: AtUri;
		cid: CID;
		value: unknown;
		blobCids: CID[];
		indexedAt: string;
		moderation: RefOf<'com.atproto.admin.defs#moderation'>;
		repo: RefOf<'com.atproto.admin.defs#repoView'>;
	};
	'com.atproto.admin.defs#recordViewDetail': {
		uri: AtUri;
		cid: CID;
		value: unknown;
		blobs: RefOf<'com.atproto.admin.defs#blobView'>[];
		labels?: RefOf<'com.atproto.label.defs#label'>[];
		indexedAt: string;
		moderation: RefOf<'com.atproto.admin.defs#moderationDetail'>;
		repo: RefOf<'com.atproto.admin.defs#repoView'>;
	};
	'com.atproto.admin.defs#recordViewNotFound': {
		uri: AtUri;
	};
	'com.atproto.admin.defs#moderation': {
		subjectStatus?: RefOf<'com.atproto.admin.defs#subjectStatusView'>;
	};
	'com.atproto.admin.defs#moderationDetail': {
		subjectStatus?: RefOf<'com.atproto.admin.defs#subjectStatusView'>;
	};
	'com.atproto.admin.defs#blobView': {
		cid: CID;
		mimeType: string;
		size: number;
		createdAt: string;
		details?: UnionOf<'com.atproto.admin.defs#imageDetails'> | UnionOf<'com.atproto.admin.defs#videoDetails'>;
		moderation?: RefOf<'com.atproto.admin.defs#moderation'>;
	};
	'com.atproto.admin.defs#imageDetails': {
		width: number;
		height: number;
	};
	'com.atproto.admin.defs#videoDetails': {
		width: number;
		height: number;
		length: number;
	};
	'com.atproto.admin.defs#subjectReviewState':
		| '#reviewOpen'
		| '#reviewEscalated'
		| '#reviewClosed'
		| (string & {});
	'com.atproto.admin.defs#reviewOpen': 'com.atproto.admin.defs#reviewOpen';
	'com.atproto.admin.defs#reviewEscalated': 'com.atproto.admin.defs#reviewEscalated';
	'com.atproto.admin.defs#reviewClosed': 'com.atproto.admin.defs#reviewClosed';
	/**
	 * Take down a subject permanently or temporarily
	 */
	'com.atproto.admin.defs#modEventTakedown': {
		comment?: string;
		/**
		 * Indicates how long the takedown should be in effect before automatically expiring.
		 */
		durationInHours?: number;
	};
	/**
	 * Revert take down action on a subject
	 */
	'com.atproto.admin.defs#modEventReverseTakedown': {
		/**
		 * Describe reasoning behind the reversal.
		 */
		comment?: string;
	};
	/**
	 * Resolve appeal on a subject
	 */
	'com.atproto.admin.defs#modEventResolveAppeal': {
		/**
		 * Describe resolution.
		 */
		comment?: string;
	};
	/**
	 * Add a comment to a subject
	 */
	'com.atproto.admin.defs#modEventComment': {
		comment: string;
		/**
		 * Make the comment persistent on the subject
		 */
		sticky?: boolean;
	};
	/**
	 * Report a subject
	 */
	'com.atproto.admin.defs#modEventReport': {
		comment?: string;
		reportType: RefOf<'com.atproto.moderation.defs#reasonType'>;
	};
	/**
	 * Apply/Negate labels on a subject
	 */
	'com.atproto.admin.defs#modEventLabel': {
		comment?: string;
		createLabelVals: string[];
		negateLabelVals: string[];
	};
	'com.atproto.admin.defs#modEventAcknowledge': {
		comment?: string;
	};
	'com.atproto.admin.defs#modEventEscalate': {
		comment?: string;
	};
	/**
	 * Mute incoming reports on a subject
	 */
	'com.atproto.admin.defs#modEventMute': {
		comment?: string;
		/**
		 * Indicates how long the subject should remain muted.
		 */
		durationInHours: number;
	};
	/**
	 * Unmute action on a subject
	 */
	'com.atproto.admin.defs#modEventUnmute': {
		/**
		 * Describe reasoning behind the reversal.
		 */
		comment?: string;
	};
	/**
	 * Keep a log of outgoing email to a user
	 */
	'com.atproto.admin.defs#modEventEmail': {
		/**
		 * The subject line of the email sent to the user.
		 */
		subjectLine: string;
		/**
		 * Additional comment about the outgoing comm.
		 */
		comment?: string;
	};
	/**
	 * Add/Remove a tag on a subject
	 */
	'com.atproto.admin.defs#modEventTag': {
		/**
		 * Tags to be added to the subject. If already exists, won't be duplicated.
		 */
		add: string[];
		/**
		 * Tags to be removed to the subject. Ignores a tag If it doesn't exist, won't be duplicated.
		 */
		remove: string[];
		/**
		 * Additional comment about added/removed tags.
		 */
		comment?: string;
	};
	'com.atproto.admin.defs#communicationTemplateView': {
		id: string;
		/**
		 * Name of the template.
		 */
		name: string;
		/**
		 * Content of the template, can contain markdown and variable placeholders.
		 */
		subject?: string;
		/**
		 * Subject of the message, used in emails.
		 */
		contentMarkdown: string;
		disabled: boolean;
		/**
		 * DID of the user who last updated the template.
		 */
		lastUpdatedBy: DID;
		createdAt: string;
		updatedAt: string;
	};
	/**
	 * Metadata tag on an atproto resource (eg, repo or record).
	 */
	'com.atproto.label.defs#label': {
		/**
		 * DID of the actor who created this label.
		 */
		src: DID;
		/**
		 * AT URI of the record, repository (account), or other resource that this label applies to.
		 */
		uri: string;
		/**
		 * Optionally, CID specifying the specific version of 'uri' resource this label applies to.
		 */
		cid?: CID;
		/**
		 * The short string name of the value or type of this label. \
		 * Maximum string length: 128
		 */
		val: string;
		/**
		 * If true, this is a negation label, overwriting a previous label.
		 */
		neg?: boolean;
		/**
		 * Timestamp when this label was created.
		 */
		cts: string;
	};
	/**
	 * Metadata tags on an atproto record, published by the author within the record.
	 */
	'com.atproto.label.defs#selfLabels': {
		/**
		 * Maximum array length: 10
		 */
		values: RefOf<'com.atproto.label.defs#selfLabel'>[];
	};
	/**
	 * Metadata tag on an atproto record, published by the author within the record. Note that schemas should use #selfLabels, not #selfLabel.
	 */
	'com.atproto.label.defs#selfLabel': {
		/**
		 * The short string name of the value or type of this label. \
		 * Maximum string length: 128
		 */
		val: string;
	};
	'com.atproto.label.subscribeLabels#labels': {
		seq: number;
		labels: RefOf<'com.atproto.label.defs#label'>[];
	};
	'com.atproto.label.subscribeLabels#info': {
		name: 'OutdatedCursor' | (string & {});
		message?: string;
	};
	'com.atproto.moderation.defs#reasonType':
		| 'com.atproto.moderation.defs#reasonSpam'
		| 'com.atproto.moderation.defs#reasonViolation'
		| 'com.atproto.moderation.defs#reasonMisleading'
		| 'com.atproto.moderation.defs#reasonSexual'
		| 'com.atproto.moderation.defs#reasonRude'
		| 'com.atproto.moderation.defs#reasonOther'
		| 'com.atproto.moderation.defs#reasonAppeal'
		| (string & {});
	'com.atproto.moderation.defs#reasonSpam': 'com.atproto.moderation.defs#reasonSpam';
	'com.atproto.moderation.defs#reasonViolation': 'com.atproto.moderation.defs#reasonViolation';
	'com.atproto.moderation.defs#reasonMisleading': 'com.atproto.moderation.defs#reasonMisleading';
	'com.atproto.moderation.defs#reasonSexual': 'com.atproto.moderation.defs#reasonSexual';
	'com.atproto.moderation.defs#reasonRude': 'com.atproto.moderation.defs#reasonRude';
	'com.atproto.moderation.defs#reasonOther': 'com.atproto.moderation.defs#reasonOther';
	'com.atproto.moderation.defs#reasonAppeal': 'com.atproto.moderation.defs#reasonAppeal';
	/**
	 * Operation which creates a new record.
	 */
	'com.atproto.repo.applyWrites#create': {
		collection: string;
		/**
		 * Maximum string length: 15
		 */
		rkey?: string;
		value: unknown;
	};
	/**
	 * Operation which updates an existing record.
	 */
	'com.atproto.repo.applyWrites#update': {
		collection: string;
		rkey: string;
		value: unknown;
	};
	/**
	 * Operation which deletes an existing record.
	 */
	'com.atproto.repo.applyWrites#delete': {
		collection: string;
		rkey: string;
	};
	'com.atproto.repo.listMissingBlobs#recordBlob': {
		cid: CID;
		recordUri: AtUri;
	};
	'com.atproto.repo.listRecords#record': {
		uri: AtUri;
		cid: CID;
		value: unknown;
	};
	'com.atproto.repo.strongRef': {
		uri: AtUri;
		cid: CID;
	};
	'com.atproto.server.createAppPassword#appPassword': {
		name: string;
		password: string;
		createdAt: string;
	};
	'com.atproto.server.createInviteCodes#accountCodes': {
		account: string;
		codes: string[];
	};
	'com.atproto.server.defs#inviteCode': {
		code: string;
		available: number;
		disabled: boolean;
		forAccount: string;
		createdBy: string;
		createdAt: string;
		uses: RefOf<'com.atproto.server.defs#inviteCodeUse'>[];
	};
	'com.atproto.server.defs#inviteCodeUse': {
		usedBy: DID;
		usedAt: string;
	};
	'com.atproto.server.describeServer#links': {
		privacyPolicy?: string;
		termsOfService?: string;
	};
	'com.atproto.server.listAppPasswords#appPassword': {
		name: string;
		createdAt: string;
	};
	'com.atproto.sync.listRepos#repo': {
		did: DID;
		/**
		 * Current repo commit CID
		 */
		head: CID;
		rev: string;
	};
	/**
	 * Represents an update of repository state. Note that empty commits are allowed, which include no repo data changes, but an update to rev and signature.
	 */
	'com.atproto.sync.subscribeRepos#commit': {
		/**
		 * The stream sequence number of this message.
		 */
		seq: number;
		/**
		 * DEPRECATED -- unused
		 * @deprecated
		 */
		rebase: boolean;
		/**
		 * Indicates that this commit contained too many ops, or data size was too large. Consumers will need to make a separate request to get missing data.
		 */
		tooBig: boolean;
		/**
		 * The repo this event comes from.
		 */
		repo: DID;
		/**
		 * Repo commit object CID.
		 */
		commit: unknown;
		/**
		 * DEPRECATED -- unused. WARNING -- nullable and optional; stick with optional to ensure golang interoperability.
		 * @deprecated
		 */
		prev?: unknown;
		/**
		 * The rev of the emitted commit. Note that this information is also in the commit object included in blocks, unless this is a tooBig event.
		 */
		rev: string;
		/**
		 * The rev of the last emitted commit from this repo (if any).
		 */
		since: string;
		/**
		 * CAR file containing relevant blocks, as a diff since the previous repo state.
		 */
		blocks: unknown;
		/**
		 * Maximum array length: 200 \
		 * List of repo mutation operations in this commit (eg, records created, updated, or deleted).
		 */
		ops: RefOf<'com.atproto.sync.subscribeRepos#repoOp'>[];
		/**
		 * List of new blobs (by CID) referenced by records in this commit.
		 */
		blobs: unknown[];
		/**
		 * Timestamp of when this message was originally broadcast.
		 */
		time: string;
	};
	/**
	 * Represents a change to an account's identity. Could be an updated handle, signing key, or pds hosting endpoint. Serves as a prod to all downstream services to refresh their identity cache.
	 */
	'com.atproto.sync.subscribeRepos#identity': {
		seq: number;
		did: DID;
		time: string;
	};
	/**
	 * Represents an update of the account's handle, or transition to/from invalid state. NOTE: Will be deprecated in favor of #identity.
	 */
	'com.atproto.sync.subscribeRepos#handle': {
		seq: number;
		did: DID;
		handle: Handle;
		time: string;
	};
	/**
	 * Represents an account moving from one PDS instance to another. NOTE: not implemented; account migration uses #identity instead
	 */
	'com.atproto.sync.subscribeRepos#migrate': {
		seq: number;
		did: DID;
		migrateTo: string;
		time: string;
	};
	/**
	 * Indicates that an account has been deleted. NOTE: may be deprecated in favor of #identity or a future #account event
	 */
	'com.atproto.sync.subscribeRepos#tombstone': {
		seq: number;
		did: DID;
		time: string;
	};
	'com.atproto.sync.subscribeRepos#info': {
		name: 'OutdatedCursor' | (string & {});
		message?: string;
	};
	/**
	 * A repo operation, ie a mutation of a single record.
	 */
	'com.atproto.sync.subscribeRepos#repoOp': {
		action: 'create' | 'update' | 'delete' | (string & {});
		path: string;
		/**
		 * For creates and updates, the new record CID. For deletions, null.
		 */
		cid: unknown;
	};
}

export interface Records {
	/**
	 * A declaration of a Bluesky account profile.
	 */
	'app.bsky.actor.profile': {
		/**
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		displayName?: string;
		/**
		 * Free-form profile description text. \
		 * Maximum string length: 2560 \
		 * Maximum grapheme length: 256
		 */
		description?: string;
		/**
		 * Small image to be displayed next to posts from account. AKA, 'profile picture'
		 */
		avatar?: AtBlob<`image/png` | `image/jpeg`>;
		/**
		 * Larger horizontal image to display behind profile view.
		 */
		banner?: AtBlob<`image/png` | `image/jpeg`>;
		/**
		 * Self-label values, specific to the Bluesky application, on the overall account.
		 */
		labels?: UnionOf<'com.atproto.label.defs#selfLabels'>;
	};
	/**
	 * Record declaring of the existence of a feed generator, and containing metadata about it. The record can exist in any repository.
	 */
	'app.bsky.feed.generator': {
		did: DID;
		/**
		 * Maximum string length: 240 \
		 * Maximum grapheme length: 24
		 */
		displayName: string;
		/**
		 * Maximum string length: 3000 \
		 * Maximum grapheme length: 300
		 */
		description?: string;
		descriptionFacets?: RefOf<'app.bsky.richtext.facet'>[];
		avatar?: AtBlob<`image/png` | `image/jpeg`>;
		/**
		 * Self-label values
		 */
		labels?: UnionOf<'com.atproto.label.defs#selfLabels'>;
		createdAt: string;
	};
	/**
	 * Record declaring a 'like' of a piece of subject content.
	 */
	'app.bsky.feed.like': {
		subject: RefOf<'com.atproto.repo.strongRef'>;
		createdAt: string;
	};
	/**
	 * Record containing a Bluesky post.
	 */
	'app.bsky.feed.post': {
		/**
		 * The primary post content. May be an empty string, if there are embeds. \
		 * Maximum string length: 3000 \
		 * Maximum grapheme length: 300
		 */
		text: string;
		/**
		 * DEPRECATED: replaced by app.bsky.richtext.facet.
		 * @deprecated
		 */
		entities?: RefOf<'app.bsky.feed.post#entity'>[];
		/**
		 * Annotations of text (mentions, URLs, hashtags, etc)
		 */
		facets?: RefOf<'app.bsky.richtext.facet'>[];
		reply?: RefOf<'app.bsky.feed.post#replyRef'>;
		embed?:
			| UnionOf<'app.bsky.embed.images'>
			| UnionOf<'app.bsky.embed.external'>
			| UnionOf<'app.bsky.embed.record'>
			| UnionOf<'app.bsky.embed.recordWithMedia'>;
		/**
		 * Indicates human language of post primary text content. \
		 * Maximum array length: 3
		 */
		langs?: string[];
		/**
		 * Self-label values for this post. Effectively content warnings.
		 */
		labels?: UnionOf<'com.atproto.label.defs#selfLabels'>;
		/**
		 * Additional hashtags, in addition to any included in post text and facets. \
		 * Maximum array length: 8 \
		 * Maximum string length: 640 \
		 * Maximum grapheme length: 64
		 */
		tags?: string[];
		/**
		 * Client-declared timestamp when this post was originally created.
		 */
		createdAt: string;
	};
	/**
	 * Record representing a 'repost' of an existing Bluesky post.
	 */
	'app.bsky.feed.repost': {
		subject: RefOf<'com.atproto.repo.strongRef'>;
		createdAt: string;
	};
	/**
	 * Record defining interaction gating rules for a thread (aka, reply controls). The record key (rkey) of the threadgate record must match the record key of the thread's root post, and that record must be in the same repository..
	 */
	'app.bsky.feed.threadgate': {
		/**
		 * Reference (AT-URI) to the post record.
		 */
		post: AtUri;
		/**
		 * Maximum array length: 5
		 */
		allow?: (
			| UnionOf<'app.bsky.feed.threadgate#mentionRule'>
			| UnionOf<'app.bsky.feed.threadgate#followingRule'>
			| UnionOf<'app.bsky.feed.threadgate#listRule'>
		)[];
		createdAt: string;
	};
	/**
	 * Record declaring a 'block' relationship against another account. NOTE: blocks are public in Bluesky; see blog posts for details.
	 */
	'app.bsky.graph.block': {
		/**
		 * DID of the account to be blocked.
		 */
		subject: DID;
		createdAt: string;
	};
	/**
	 * Record declaring a social 'follow' relationship of another account. Duplicate follows will be ignored by the AppView.
	 */
	'app.bsky.graph.follow': {
		subject: DID;
		createdAt: string;
	};
	/**
	 * Record representing a list of accounts (actors). Scope includes both moderation-oriented lists and curration-oriented lists.
	 */
	'app.bsky.graph.list': {
		/**
		 * Defines the purpose of the list (aka, moderation-oriented or curration-oriented)
		 */
		purpose: RefOf<'app.bsky.graph.defs#listPurpose'>;
		/**
		 * Display name for list; can not be empty. \
		 * Minimum string length: 1 \
		 * Maximum string length: 64
		 */
		name: string;
		/**
		 * Maximum string length: 3000 \
		 * Maximum grapheme length: 300
		 */
		description?: string;
		descriptionFacets?: RefOf<'app.bsky.richtext.facet'>[];
		avatar?: AtBlob<`image/png` | `image/jpeg`>;
		labels?: UnionOf<'com.atproto.label.defs#selfLabels'>;
		createdAt: string;
	};
	/**
	 * Record representing a block relationship against an entire an entire list of accounts (actors).
	 */
	'app.bsky.graph.listblock': {
		/**
		 * Reference (AT-URI) to the mod list record.
		 */
		subject: AtUri;
		createdAt: string;
	};
	/**
	 * Record representing an account's inclusion on a specific list. The AppView will ignore duplicate listitem records.
	 */
	'app.bsky.graph.listitem': {
		/**
		 * The account which is included on the list.
		 */
		subject: DID;
		/**
		 * Reference (AT-URI) to the list record (app.bsky.graph.list).
		 */
		list: AtUri;
		createdAt: string;
	};
}
